-- 1. Create items table if it doesn't exist
create table if not exists items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  image_url text,
  category text,
  price numeric default 0,
  tag text
);

-- 2. Enable Security
alter table items enable row level security;

-- 3. Allow everyone to read items
create policy "Allow public read access"
on items for select
to public
using (true);

-- 4. Insert dummy data (if empty)
insert into items (name, description, image_url, category, price, tag)
select 'Roșii', 'Roșii proaspete și dulci, perfecte pentru salate.', 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=400&q=80', 'Legume', 0, 'Legume'
where not exists (select 1 from items where name = 'Roșii');

insert into items (name, description, image_url, category, price, tag)
select 'Castraveți', 'Castraveți crocanți locali.', 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?auto=format&fit=crop&w=400&q=80', 'Legume', 0, 'Legume'
where not exists (select 1 from items where name = 'Castraveți');

insert into items (name, description, image_url, category, price, tag)
select 'Ardei', 'Ardei gras colorat și plin de vitamine.', 'https://images.unsplash.com/photo-1563565375-f3fdf5d6c4a3?auto=format&fit=crop&w=400&q=80', 'Legume', 0, 'Legume'
where not exists (select 1 from items where name = 'Ardei');

insert into items (name, description, image_url, category, price, tag)
select 'Cartofi', 'Cartofi noi, excelenți la cuptor.', 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=400&q=80', 'Legume', 0, 'Legume'
where not exists (select 1 from items where name = 'Cartofi');

insert into items (name, description, image_url, category, price, tag)
select 'Mere', 'Mere ionatan dulci-acrișoare.', 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=400&q=80', 'Fructe', 0, 'Fructe'
where not exists (select 1 from items where name = 'Mere');

insert into items (name, description, image_url, category, price, tag)
select 'Pere', 'Pere zemoase de toamnă.', 'https://images.unsplash.com/photo-1631160299919-6a175aa6d189?auto=format&fit=crop&w=400&q=80', 'Fructe', 0, 'Fructe'
where not exists (select 1 from items where name = 'Pere');

insert into items (name, description, image_url, category, price, tag)
select 'Miere', 'Miere polifloră naturală.', 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=400&q=80', 'Altele', 0, 'Altele'
where not exists (select 1 from items where name = 'Miere');
